# -*- coding: utf-8 -*-
"""streaming-crypto(sorgu)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139VBX5yVApIqTe1NGmwNk7uNV2n3SUTW
"""

import pandas as pd

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, isnan, when, count
from pyspark.sql.functions import split, unix_timestamp,when, col, sum ,year, month, dayofweek, hour,date_format ,  mean
from datetime import time
import plotly.express as px

spark=SparkSession.builder.appName("stream_crypto").getOrCreate()

fil=spark.read.csv('/content/sample_data/crypto_prc.csv', header=True, inferSchema=True)

fil.select([count(when(col(c).isNull(), c)).alias(c) for c in fil.columns]).show()

fil.show(10)

fil.select("data").show(5)

saat=fil.withColumn("saat", split(fil["data"], " ")[1]).show(5)
tarih=fil.withColumn("tarih", split(fil["data"], " ")[0]).show(5)